version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the React app...
      - bun install
      - bun run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying S3...
      - aws s3 sync ./dist s3://$S3_BUCKET_NAME --delete
